# Generated by Django 5.2.4 on 2025-07-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
